max_tokens_per_step: 128
max_actions_per_traj: 10

env_manager_cls: roll.pipeline.agentic.env_manager.traj_env_manager.TrajEnvManager
gem_qa:
  # RuleTaker Environments
  RuleTaker-d0:
    env_type: "logic:RuleTaker-d0"
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: ${env_manager_cls}
    agent_system_template: ${qa_agent_system_template}
    agent_template: ${qa_agent_template}
    env_config:
      dataset_name: axon-rl/RuleTaker-d0-70k
  RuleTaker-d1:
    env_type: "logic:RuleTaker-d1"
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: ${env_manager_cls}
    agent_system_template: ${qa_agent_system_template}
    agent_template: ${qa_agent_template}
    env_config:
      dataset_name: axon-rl/RuleTaker-d1-70k
  RuleTaker-d2:
    env_type: "logic:RuleTaker-d2"
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: ${env_manager_cls}
    agent_system_template: ${qa_agent_system_template}
    agent_template: ${qa_agent_template}
    env_config:
      dataset_name: axon-rl/RuleTaker-d2-70k
  RuleTaker-d3:
    env_type: "logic:RuleTaker-d3"
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: ${env_manager_cls}
    agent_system_template: ${qa_agent_system_template}
    agent_template: ${qa_agent_template}
    env_config:
      dataset_name: axon-rl/RuleTaker-d3-70k
  RuleTaker-d5:
    env_type: "logic:RuleTaker-d5"
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: ${env_manager_cls}
    agent_system_template: ${qa_agent_system_template}
    agent_template: ${qa_agent_template}
    env_config:
      dataset_name: axon-rl/RuleTaker-d5-70k

  # QA Environments
  NaturalQuestions:
    env_type: "qa:NaturalQuestions"
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: ${env_manager_cls}
    agent_system_template: ${qa_agent_system_template}
    agent_template: ${qa_agent_template}
    env_config:
      dataset_name: axon-rl/NaturalQuestions
  HotpotQA:
    env_type: "qa:HotpotQA"
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: ${env_manager_cls}
    agent_system_template: ${qa_agent_system_template}
    agent_template: ${qa_agent_template}
    env_config:
      dataset_name: axon-rl/HotpotQA

qa_agent_system_template: You're a helpful assistant.
qa_agent_template: "{observation}"

