all_response_pattern: ^(.*)$
action_pattern: <answer>(.*?)</answer>
think_action_pattern: <think>(.*?)</think>\s*<answer>(.*?)</answer>

max_tokens_per_step: 128
max_actions_per_traj: 10
sokoban_format_penalty: -0.15
frozen_format_penalty: -0.01

custom_env:
  SimpleSokoban:
    env_type: sokoban
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: roll.pipeline.agentic.env_manager.vl_traj_env_manager.VLTrajEnvManager
    use_thread_lock: true
    agent_system_template: ${agent_system_template}
    pre_step_template: ${pre_step_template}
    next_step_template: ${next_step_template}
    env_config: # keys should be a subset of SokobanConfig
      action_pattern: ${action_pattern}
      max_steps: ${max_actions_per_traj}
      format_penalty: ${sokoban_format_penalty}
      dim_room: [6, 6]
      num_boxes: 1
      render_mode: "rgb_array"
  LargerSokoban:
    env_type: sokoban
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: roll.pipeline.agentic.env_manager.vl_traj_env_manager.VLTrajEnvManager
    use_thread_lock: true
    agent_system_template: ${agent_system_template}
    pre_step_template: ${pre_step_template}
    next_step_template: ${next_step_template}
    env_config:
      action_pattern: ${action_pattern}
      max_steps: ${max_actions_per_traj}
      format_penalty: ${sokoban_format_penalty}
      dim_room: [10, 10]
      num_boxes: 2
      search_depth: 10
      render_mode: "rgb_array"
  SokobanDifferentGridVocab:
    env_type: sokoban
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: roll.pipeline.agentic.env_manager.vl_traj_env_manager.VLTrajEnvManager
    use_thread_lock: true
    agent_system_template: ${agent_system_template}
    pre_step_template: ${pre_step_template}
    next_step_template: ${next_step_template}
    env_config: # keys should be a subset of SokobanConfig
      action_pattern: ${action_pattern}
      format_penalty: ${sokoban_format_penalty}
      search_depth: 30
      dim_room: [6, 6]
      num_boxes: 1
      max_steps: ${max_actions_per_traj}
      grid_lookup: { 0: "W", 1: ".", 2: "G", 3: "C", 4: "B", 5: "A", 6: "@" }
      grid_vocab: { "W": "wall", ".": "empty", "G": "target", "C": "box on target", "B": "box", "A": "player", "@": "player on target" }
      render_mode: "rgb_array"
  FrozenLake:
    env_type: frozen_lake
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: roll.pipeline.agentic.env_manager.vl_traj_env_manager.VLTrajEnvManager
    use_thread_lock: true
    agent_system_template: ${agent_system_template}
    pre_step_template: ${pre_step_template}
    next_step_template: ${next_step_template}
    env_config:
      action_pattern: ${action_pattern}
      max_steps: ${max_actions_per_traj}
      format_penalty: ${frozen_format_penalty}
      is_slippery: false
      render_mode: "rgb_array"
  FrozenLakeThink:
    env_type: frozen_lake
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: roll.pipeline.agentic.env_manager.vl_traj_env_manager.VLTrajEnvManager
    use_thread_lock: true
    agent_system_template: ${agent_system_template}
    pre_step_template: ${pre_step_template}
    next_step_template: ${next_step_template}
    env_config:
      action_pattern: ${think_action_pattern}
      max_steps: ${max_actions_per_traj}
      format_penalty: ${frozen_format_penalty}
      is_slippery: false
      render_mode: "rgb_array"

agent_system_template: "You're a helpful assistant. You are a good game player. You are aiming to get high reward in the game."
pre_step_template: |
  {observation}
  Turn {turn_idx}:
  Current state is:

next_step_template: |
  Enter your move.
  Strictly follow this format.
  You have {actions_left} actions left. 
  Max response length: {max_response_length} words (tokens).
